language: php

php:
    - 5.3

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=1

# The following git: and befire_install: hackery is used to allow Travis to access the git submodules 
# without changing the submodule URL in the .gitmodules file
git:
    submodules: false
# Use sed to replace the SSH URL with the public https URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
#/end hackery for submodules
# The above was taken from http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
